spring:
  application:
    name: eureka-registry

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}