# DataSource Config
spring:
  datasource:
    url: jdbc://mysql://localhost:3306/trial?characterEncoding=UTF-8&serverTimeZone=GMT%2b8:00
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root